[package]
name = "mayara"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.15", features = ["derive"] }
clap-verbosity-flag = "2.2.1"
env_logger = "0.11.5"
log = "0.4.22"
socket2 = "0.5.7"
time = { version = "0.3.36", features = ["formatting"] }
tokio = { version = "1", features = ["full"] }
tokio-shutdown = "0.1.4"

