name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  linux_x86_64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build static
      uses: stevenleadbeater/rust-musl-builder@master
      with:
          args: /bin/bash -c "cargo build --release --target=x86_64-unknown-linux-musl"
    - name: Run tests
      uses: stevenleadbeater/rust-musl-builder@master
      with:
          args: /bin/bash -c "cargo test --release --verbose"
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Mayara Linux x86_64
        path: target/release/mayara

  macos:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release
    - name: Run tests
      run: cargo test --release --verbose
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Mayara macOS Intel
        path: target/release/mayara

  macos_arm64:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release
    - name: Run tests
      run: cargo test --release --verbose
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Mayara macOS Apple Silicon
        path: target/release/mayara

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release
    - name: Run tests
      run: cargo test --release --verbose
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Mayara Windows x86_64
        path: target/release/mayara.exe
